

# 异常的概念

程序在运行过程中，由于我们的编码不规范，或者其他原因一些客观原因，导致我们的程序无法继续运行，此时，程序就会出现异常。如果我们不对异常进行处理，程序可能会由于异常直接中断掉。为了保证程序的健壮性，我们在程序设计里提出了异常处理这个概念。

本次只是让大家初步体验一下异常，以及异常的简单处理，后续关于异常，我们还会再次深入学习。

## 读取文件异常

在读取一个文件时，如果这个文件不存在，则会报出`FileNotFoundError`错误。 ![img](imgs/异常.png)程序在运行过程中会经常遇到类似的异常，如果我们不进行处理，此时程序就会中断并退出。为了提高程序的健壮性，我们可以使用异常处理机制来解决程序运行过程中可能出现的问题。

## try...except语句

try...except语句可以对代码运行过程中可能出现的异常进行处理。 语法结构:

```python
try:
    可能会出现异常的代码块
except 异常的类型:
    出现异常以后的处理语句
```

示例：

```python
try:
    f = open('test.txt', 'r')
    print(f.read())
except FileNotFoundError:
    print('文件没有找到,请检查文件名称是否正确')
```

## 练习:

让用户任意输入两个数字，再让用户选择算数运算符，最后让用户输入的两个数字进行算数运算，并输出结果。 要求：

- 如果用户输入的内容不是数字，需要提示用户重新输入
- 如果用户做了除以0的操作，提示用户不能除以0

参考代码:

```python
def get_num(msg):
    num = input(msg)
    try:
        num = float(num)
    except ValueError:
        print("您输入的数字不合法，请重新输入")
        get_num(msg)
    else:
        return num


def get_operator():
    operator = input('请选择运算符\n 1:加法 2:减法 3:乘法 4:除法 \n')
    if operator != '1' and operator != '2' and operator != '3' and operator != '4':
        get_operator()
    else:
        return operator


def do_cal(a, b, p):
    if p == '1':
        return a + b
    elif p == '2':
        return a - b
    elif p == '3':
        return a * b
    elif p == '4':
        try:
            result = a / b
        except ZeroDivisionError:
            return '对不起，除数不能为0'
        else:
            return result
    else:
        return '对不起，不支持的运算符'

while True:
    num1 = get_num("请输入一个数字\n")
    num2 = get_num('请再输入一个数字\n')
    operator = get_operator()
    result = do_cal(num1, num2, operator)

    print('计算的结果是:{}'.format(result))
    print('#############################')
```