## 异常

程序在运行过程中，由于我们的编码不规范，或者其他原因一些客观原因，导致我们的程序无法继续运行，此时，程序就会出现异常。如果我们不对异常进行处理，程序可能会由于异常直接中断掉。为了保证程序的健壮性，我们在程序设计里提出了异常处理这个概念。

当Python检测到一个错误时，解释器就无法继续执行了，反而出现了一些错误的提示，这就是所谓的"异常

### 捕获异常：

```python
num = input('数字：')
num2 = input('数字：')
try:
    num = int(num)
    num1 = int(num2)
    print(num/num1)
except:
    print('程序出错了')
```

这里不会报错，只会返回程序出错了

#### 捕获指定异常

```python
try:
    print(num)
except IOError:
    print('产生错误了')
```

except捕获的异常类型是IOError，当产生其他异常时，依然会报错

```python
try:
    print(num)
except NameError:
    print('变量使用出现错误')
```

## 捕获多个指定异常

```python
try:
    print('-----test--1---')
    open('123.txt','r') # 如果123.txt文件不存在，那么会产生 IOError 异常
    print('-----test--2---')
    print(num)# 如果num变量没有定义，那么会产生 NameError 异常

except (IOError,NameError): 
    #如果想通过一次except捕获到多个异常可以用一个元组的方式
    pass
```

当捕获多个异常时，把要捕获的异常的名字，放到except 后，并使用元组的方式进行存储

还可以把返回的异常信息打印出来

用except IOError as result:

​		print(result)

### try...except...else

当没有捕获到异常时会执行else中的代码

```python
try: num = 100 
    print(num) 
except NameError as errorMsg: 
 	print('产生错误了:%s'%errorMsg) 
else: 
    print('没有捕获到异常，真高兴')
```

## try..finally...

在程序中，如果一个段代码必须要执行，即无论异常是否产生都要执行，那么此时就需要使用finally。 比如文件关闭，释放锁，把数据库连接返还给连接池等。

```python
try:
    f = open('test.txt')
    try:
        while True:
            content = f.readline()
            if len(content) == 0:
                break
            print(content)
    except:
        #如果在读取文件的过程中，产生了异常，那么就会捕获到
        #比如 按下了 ctrl+c
        pass
    finally:
        f.close()
        print('关闭文件')
except:
    print("没有这个文件")
```

# with关键字的使用

对于系统资源如文件、数据库连接、socket 而言，应用程序打开这些资源并执行完业务逻辑之后，必须做的一件事就是要关闭（断开）该资源。

比如 Python 程序打开一个文件，往文件中写内容，写完之后，就要关闭该文件，否则会出现什么情况呢？极端情况下会出现 "Too many open files" 的错误，因为系统允许你打开的最大文件数量是有限的。

同样，对于数据库，如果连接数过多而没有及时关闭的话，就可能会出现 "Can not connect to MySQL server Too many connections"，因为数据库连接是一种非常昂贵的资源，不可能无限制的被创建。

```python
def m3():
    with open("output.txt", "r") as f:
        f.write("Python之禅")
Copy
```

一种更加简洁、优雅的方式就是用 with 关键字。open 方法的返回值赋值给变量 f，当离开 with 代码块的时候，系统会自动调用 f.close() 方法， with 的作用和使用 try/finally 语句是一样的。

## try嵌套中

```python
try:
    f = open('test.txt')
    try:
        while True:
            content = f.readline()
            if len(content) == 0:
                break
            print(content)
    finally:
        f.close()
        print('关闭文件')
except:
    print("文件读取出错")
Copy
```

运行结果:

```python
xxxxxxx--->这是test.txt文件中读取到信息
^C关闭文件
文件读取出错
```

